version: '3.7'

services:
  backend:
    image: iacqueuecraft-backend:latest
    volumes:
      - ./Backend:/app
    ports:
      - "5000:5000"
    deploy:
      replicas: 1

  worker:
    image: iacqueuecraft-worker:latest
    volumes:
      - ./Worker:/app
    ports:
      - "5005"
    deploy:
      replicas: 1

  frontend:
    image: iacqueuecraft-frontend:latest
    ports:
      - "5001:5001"
    volumes:
      - ./Frontend:/app
    deploy:
      replicas: 1

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    deploy:
      replicas: 1

  rq-dashboard:
    image: rq-dashboard:latest
    ports:
      - '9181:9181'
    deploy:
      replicas: 1

  scaler:
    image: iacqueuecraft-scaler:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1

  gitlab:
    image: gitlab/gitlab-ee:16.10.6-ee.0
    restart: always
    hostname: 'gitlab.example.com'
    ports:
      - "22:22"
      - "80:80"
    volumes:
      - $GITLAB_HOME/data:/var/opt/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/config:/etc/gitlab 
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

configs:
  gitlab:
    file: ./gitlab.rb

secrets:
  gitlab_root_password:
    file: ./root_password.txt
  postgres_password:
    file: ./postgres_password.txt

volumes:
  postgres_data:
